# Generated by Django 2.2.3 on 2020-04-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200414_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='cast', to='movies.Staff'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director', to='movies.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
