# Generated by Django 2.2.3 on 2020-04-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200429_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
