# Generated by Django 2.2.3 on 2020-04-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_staff_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
