# Generated by Django 2.2.3 on 2020-05-11 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0013_moviecomment_moviecommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='commentdislike',
            field=models.ManyToManyField(related_name='commentdislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='commentlike',
            field=models.ManyToManyField(related_name='commentlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
