# Generated by Django 2.2.3 on 2020-05-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
