# Generated by Django 2.2.3 on 2020-05-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20200518_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
