# Generated by Django 2.2.3 on 2020-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20200519_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_artists',
            field=models.ManyToManyField(related_name='liked_artists', to='movies.Artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followed_artists',
            field=models.ManyToManyField(related_name='followed_artists', to='movies.Artist'),
        ),
    ]
