# Generated by Django 2.2.3 on 2020-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20200519_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='artist',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
