# Generated by Django 2.2.3 on 2020-05-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20200519_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchlisted',
            field=models.IntegerField(default=0),
        ),
    ]
