# Generated by Django 2.2.3 on 2020-05-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20200519_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='views',
        ),
        migrations.AddField(
            model_name='artist',
            name='movies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='series',
            field=models.IntegerField(default=0),
        ),
    ]
