# Generated by Django 2.2.3 on 2020-05-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20200520_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
