# Generated by Django 2.2.3 on 2020-05-20 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_auto_20200520_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='series',
        ),
    ]
