# Generated by Django 2.2.3 on 2020-05-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_auto_20200527_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='watchedlist',
            new_name='moviewatchedlist',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='watchlist',
            new_name='moviewatchlist',
        ),
    ]
