# Generated by Django 2.2.3 on 2020-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_auto_20200527_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='runningtime',
            field=models.IntegerField(default=90),
        ),
    ]
