# Generated by Django 2.2.3 on 2020-05-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_auto_20200527_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='season',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='series',
            name='poster',
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='episode/images/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='season/images/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='series/images/'),
        ),
    ]
