# Generated by Django 2.2.3 on 2020-05-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_auto_20200527_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
