# Generated by Django 2.2.3 on 2020-05-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_episode_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='season',
            name='cast',
        ),
        migrations.AddField(
            model_name='episode',
            name='maincast',
            field=models.ManyToManyField(related_name='episodemaincast', to='movies.Artist'),
        ),
        migrations.AddField(
            model_name='season',
            name='maincast',
            field=models.ManyToManyField(related_name='seasonmaincast', to='movies.Artist'),
        ),
    ]
