# Generated by Django 2.2.3 on 2020-05-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_auto_20200528_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tomatometer',
            field=models.IntegerField(default=0),
        ),
    ]
