# Generated by Django 2.2.3 on 2020-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0038_auto_20200603_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='series_favorite',
            field=models.ManyToManyField(related_name='series_favorite', to='movies.Series'),
        ),
        migrations.AddField(
            model_name='profile',
            name='series_watched',
            field=models.ManyToManyField(related_name='series_watched', to='movies.Series'),
        ),
        migrations.AddField(
            model_name='profile',
            name='series_watchlist',
            field=models.ManyToManyField(related_name='series_watchlist', to='movies.Series'),
        ),
    ]
