# Generated by Django 2.2.3 on 2020-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0039_auto_20200603_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='nationality',
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.ManyToManyField(to='movies.Country'),
        ),
        migrations.AddField(
            model_name='artist',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
