# Generated by Django 2.2.3 on 2020-06-09 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0043_auto_20200609_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviecommentreply',
            name='target_comment',
        ),
        migrations.RemoveField(
            model_name='moviecommentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followed_artists',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_artists',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_movies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='moviewatchedlist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='moviewatchlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='artist_favorite',
            field=models.ManyToManyField(related_name='artist_favorite', to='movies.Artist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='artist_followed',
            field=models.ManyToManyField(related_name='artist_followed', to='movies.Artist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='movie_favorite',
            field=models.ManyToManyField(related_name='movie_favorite', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='movie_watched',
            field=models.ManyToManyField(related_name='movie_watched', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='movie_watchlist',
            field=models.ManyToManyField(related_name='movie_watchlist', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='MovieComment',
        ),
        migrations.DeleteModel(
            name='MovieCommentReply',
        ),
    ]
