# Generated by Django 2.2.3 on 2020-06-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0044_auto_20200609_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
