# Generated by Django 2.2.3 on 2020-06-12 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0045_auto_20200609_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='episode_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='episode_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='season_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('runningtime', models.IntegerField(default=90)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('watched', models.IntegerField(default=0)),
                ('watchlisted', models.IntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('metascore', models.IntegerField(default=0)),
                ('tomatometer', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='franchises/images/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ManyToManyField(to='movies.Country')),
                ('director', models.ManyToManyField(related_name='franchisedirector', to='movies.Artist')),
                ('genre', models.ManyToManyField(to='movies.Genre')),
                ('language', models.ManyToManyField(to='movies.Language')),
                ('maincast', models.ManyToManyField(related_name='franchisecast', to='movies.Artist')),
                ('movies', models.ManyToManyField(to='movies.Movie')),
                ('mpa_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.MPA_Rating')),
                ('producer', models.ManyToManyField(related_name='franchiseproducer', to='movies.Artist')),
                ('production', models.ManyToManyField(to='movies.Production')),
                ('supportingcast', models.ManyToManyField(related_name='franchisesupportingcast', to='movies.Artist')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writer', models.ManyToManyField(related_name='franchisewriter', to='movies.Artist')),
            ],
        ),
    ]
