# Generated by Django 2.2.3 on 2020-06-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0046_auto_20200612_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tomatometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='tomatometer',
            field=models.IntegerField(default=0),
        ),
    ]
