# Generated by Django 2.2.3 on 2020-06-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0047_auto_20200615_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='episode_count',
        ),
        migrations.RemoveField(
            model_name='season',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='series',
            name='episode_count',
        ),
        migrations.RemoveField(
            model_name='series',
            name='season_count',
        ),
        migrations.RemoveField(
            model_name='series',
            name='seasons',
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Season'),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Series'),
        ),
    ]
