# Generated by Django 2.2.3 on 2020-07-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0051_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailervideo',
            field=models.FileField(blank=True, null=True, upload_to='movies/trailers/'),
        ),
        migrations.AddField(
            model_name='series',
            name='trailervideo',
            field=models.FileField(blank=True, null=True, upload_to='movies/trailers/'),
        ),
    ]
