# Generated by Django 2.2.3 on 2020-07-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0053_auto_20200706_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AlterField(
            model_name='series',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='series/trailers/'),
        ),
    ]
