# Generated by Django 2.2.3 on 2020-07-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0054_auto_20200707_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
    ]
