# Generated by Django 2.2.3 on 2020-07-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0055_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productions/'),
        ),
    ]
