# Generated by Django 2.2.3 on 2020-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0056_production_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
