# Generated by Django 2.2.3 on 2020-07-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0059_auto_20200716_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
